# NOTE: Generated By HttpRunner v3.1.4
# FROM: testcases\api_login_list.yml


import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase

from testcases.api_login_test import TestCaseApiLogin as ApiLogin


class TestCaseApiLoginList(HttpRunner):

    config = Config("list").base_url("http://api.keyou.site:8000").verify(False)

    teststeps = [
        Step(RunTestCase("login").call(ApiLogin).export(*["token"])),
        Step(
            RunRequest("get_list")
            .get("/projects/")
            .with_params(**{"page": 1, "size": 5})
            .with_headers(**{"Authorization": "JWT $token"})
            .validate()
            .assert_equal("status_code", 200)
        ),
    ]


if __name__ == "__main__":
    TestCaseApiLoginList().test_start()
