# NOTE: Generated By HttpRunner v3.1.4
# FROM: testcases\api_login_api.yml

import allure
from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase

@allure.epic("环保系统")
@allure.feature("登录系统")
class TestCaseApiLoginApi(HttpRunner):

    config = (
        Config("登录")
        .variables(**{"username": "keyou1", "password": 123456})
        .base_url("http://api.keyou.site:8000")
        .verify(False)
        .export(*["token"])
    )

    teststeps = [
        Step(
            RunRequest("登录")
            .post("/user/login/")
            .with_headers(**{"Content-Type": "application/json"})
            .with_json({"username": "$username", "password": "$password"})
            .extract()
            .with_jmespath("body.token", "token")
            .validate()
            .assert_equal("status_code", 200)
            .assert_contains("body", "token")
        ),
    ]


if __name__ == "__main__":
    TestCaseApiLoginApi().test_start()
