# NOTE: Generated By HttpRunner v3.1.4
# FROM: testcases\api_login_list.yml
import allure

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase

from testcases.api_login_api_test import TestCaseApiLoginApi as ApiLoginApi

@allure.epic("环保系统")
class TestCaseApiLoginList(HttpRunner):

    config = Config("获取列表").base_url("http://api.keyou.site:8000").verify(False)

    teststeps = [
        Step(RunTestCase("登录").call(ApiLoginApi).export(*["token"])),
        Step(
            RunRequest("获取列表")
            .get("/projects/")
            .with_params(**{"page": 1, "size": 5})
            .with_headers(**{"Authorization": "JWT $token"})
            .validate()
            .assert_equal("status_code", 200)
        ),
    ]


if __name__ == "__main__":
    TestCaseApiLoginList().test_start()
