# NOTE: Generated By HttpRunner v3.1.4
# FROM: testcases\api_login.yml


import pytest
from httprunner import Parameters


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseApiLogin(HttpRunner):
    @pytest.mark.parametrize(
        "param",
        Parameters(
            {"title-username-password-status_code-body_msg": "${get_accounts()}"}
        ),
    )
    def test_start(self, param):
        super().test_start(param)

    config = (
        Config("登录")
        .base_url("http://api.keyou.site:8000")
        .verify(False)
        .export(*["token"])
    )

    teststeps = [
        Step(
            RunRequest("$title")
            .post("/user/login/")
            .with_headers(**{"Content-Type": "application/json"})
            .with_json({"username": "$username", "password": "$password"})
            .extract()
            .with_jmespath("body.token", "token")
            .validate()
            .assert_equal("status_code", "$status_code")
            .assert_contains("body", "$body_msg")
        ),
    ]


if __name__ == "__main__":
    TestCaseApiLogin().test_start()
